### ISSUE TITLE
[MySQL] Errors with paths

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgsqlive#25] opened 2019-08-19 06:56 UTC
When trying in a path, if it has an extra space at the end, the app complains.
If you supply a path to save a .sql file without specifying the name of the file (let's say, a directory to save it to) it complains.

**Comment by omfgitsmark** [comment] 2019-08-25 02:36
Well, what do you think the default name for the file should be?

I'm thinking just `mtg.sql`, thoughts?

EDIT: I can't seem to recreate any problems with having an extra space. Can you provide exact steps?

**Comment by ZeldaZach** [comment] 2019-08-27 23:03
`mtgjson_4.5.0.sql` if possible. Also, the problem is most likely a missing `strip()` at the end of user parsing. I don't expect spaces to be captured at the end tho... weird

**Comment by ancestral** [comment] 2019-08-27 23:59
The name doesn’t matter much to me!

**Comment by omfgitsmark** [comment] 2019-08-28 03:18
I think it's all fixed, I added strips to basically everything even though I thought argparse automatically did that. I ended up making the default `mtgjson.sql` but I'll append the version number on there because that's a good idea.

**Comment by omfgitsmark** [comment] 2019-09-24 12:34
pretty sure this can be closed, and I can't close it :(

**Closed as completed** 2019-09-24 13:16 UTC
